name: Deploy Angular to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: required-remainder-backend
      IMAGE_TAG: ${GITHUB_SHA::7}
      EB_APPLICATION_NAME: required-remainder-backend
      EB_ENVIRONMENT_NAME: required-remainder-backend-env
      S3_BUCKET: required-remainder-fe-bucket
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless

    - name: Build Angular app (client-side only)
      run: npm run build -- --configuration production

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get build output directory
      id: get-output-dir
      run: |
        # Read the output path from angular.json dynamically
        OUTPUT_DIR=$(node -e "
          const config = require('./angular.json');
          const projectName = Object.keys(config.projects)[0];
          console.log(config.projects[projectName].architect.build.options.outputPath);
        ")
        echo "output_dir=$OUTPUT_DIR" >> $GITHUB_OUTPUT
        echo "Build output directory: $OUTPUT_DIR"

    - name: Upload to S3
      run: |
        aws s3 sync ${{ steps.get-output-dir.outputs.output_dir }}/ s3://required-remainder-fe-bucket --delete

    - name: Invalidate CloudFront cache
      run: |
        if [ ! -z "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
          echo "CloudFront cache invalidated successfully"
        else
          echo "No CloudFront Distribution ID provided - skipping cache invalidation"
        fi
      continue-on-error: true
